### ISSUE TITLE
No need for `return h('div')`?

### ISSUE THREAD

**Issue by niuage** [lupas/vue3-keypress#2]
Wasn't sure where to post that but basically I don't think you need to render an empty div.

Personally, these 2 options work for me:

```
render() { return null; }
```

or

```
render() { h(() => null); }
```

In the doc, they mention that if you pass a function that returns null, then it renders a comment. https://v3.vuejs.org/api/global-api.html#h

I think either is better than rendering an empty div.

Edit: actually, a third option would be to not even include the render function, and it seems like it just outputs an html comment as well.

**Comment by lupas** [comment]
You're right - for some reason when testing it I got the vue warning, but it is gone now too when testing it again.

Just released v3.0.1 which fixes this, thanks for the input!

**Comment by lupas** [comment]
@niuage 

Just saw your "edit".

When I delete the render function it works but I get the following warning:
>runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Component is missing template or render function. 
  at <Keypress key-event="keyup" key-code=65 modifiers= ["shiftKey"]  ... > 
  at <AsyncComponentWrapper key-event="keyup" key-code=65 modifiers= ["shiftKey"]  ... > 
  at <SingleEventSingleKeycode key=0 > 
  at <App>

**Comment by niuage** [comment]
Ah yes, you're right, I tested that last, just looked at the generated html, saw it just output comments and concluded it was fine, but there's indeed a warning 👍
