### ISSUE TITLE
[Refactor] Pass @success handlers via props & move away from component-based approach

### ISSUE THREAD

**Issue by lupas** [lupas/vue3-keypress#3]
As discussed in https://github.com/lupas/vue3-keypress/issues/1 with @niuage, this module's usage could be simplified through two optimisations:

- Ability to pass success method via props, so no "triage" of success events is needed in the event handler method
- Move away from a component-based module to a pure Javascript module that can be used within the setup() function

Example usage:

```js
import useKeypress from 'vue3-keypress'

export default {
  setup() {
    const keyPressConfig = {
      keyEvent: 'keyup',
      keyBinds: [
        {
          keyCode: 65, // A
          modifiers: ['shiftKey'],
          success: handleAPressed,
          preventDefault: true,
        },
        {
          keyCode: 83, // S
          modifiers: ['shiftKey'],
          success: handleBPressed,
          preventDefault: false,
        },
      ],
    }

    useKeypress(keyPressConfig)

    return { }
  },
}
```

**Comment by niuage** [comment]
👍  

I do think moving away from the component approach is a good idea, but a super important feature (for me) that we need to retain is the adding/removing of listeners on mount/unmount.

Right now, I'm using Keypress for a dropdown, and I want the up and down keys to be affecting the dropdown selection only when the dropdown is opened:

```vue
<template>
    <!- html... ->
    <template v-if="opened">
        <Keypress ...></Keypress>
    </template>    
</template>
```

This way, when `opened` is true, it setups the events, and when it's false, all the listeners are removed automatically.

I think a way to do that would be to accept a `ref`, and then `useKeypress ` can use `watch` (`import { watch } from 'vue';`), to react to this ref changes, and add or remove listeners based on it?

**Comment by niuage** [comment]
Another thought is that you might want to support both `useKeypress ` and the old component based approach, as I think vue3 still supports the old `data`/`methods`/`computed` syntax, so it might still be useful?

Although, you could probably use `useKeypress` in the mount and unmount callbacks when writing a component the old-fashion way, so maybe there's no need.

**Comment by lupas** [comment]
Yep, the automatic addition of the listener(s) is imho key, don't want to get rid of that.
The watch idea might work well, would need to test that.

About the "compatibility":
Yep, probably true. Though I don't want to keep this module too complicated to maintain, it was just a quick botch job I did when I needed such a functionality a while ago. So wanna keep it as simple & easy to maintain as possible.

**Comment by lupas** [comment]
Released all with [v4.0.0](https://github.com/lupas/vue3-keypress/releases/tag/v4.0.0)

**Comment by tbredin** [comment]
Hello, quick question as I am in a tricky position in my team — we are now on Vue 3 but the process of moving to composition API is going to be a little slow — did the options API end up still being supported with this package in v3? 

And if so, what would be the recommended syntax? 

Thanks!

**Comment by lupas** [comment]
@tbredin 
Since v4.0.0 we support only the composition API.

You can keep using [v3.0.2](https://github.com/lupas/vue3-keypress/tree/v3.0.2) and the syntax described in the readme there, that should still work for you.
