### ISSUE TITLE
NPM package empty

### ISSUE THREAD

**Issue by themoenen** [lupas/vue3-keypress#5]
It seems like your npm package is missing the actual script. Only @types › index.ts and package.json are present.

**Comment by therealryanbonham** [comment]
Also seeing this same error.

**Comment by HelloAllan** [comment]
Seeing the same issue, although `4.0.0-beta3` does contain the lib files.

**Comment by morr** [comment]
@lupas publish it please

**Comment by lupas** [comment]
Sorry guys for that - just re-published to NPM, lib folder should be there now.

https://github.com/lupas/vue3-keypress/releases/tag/v4.0.1
