### ISSUE TITLE
Missing link for 'mapped string' in the README

### ISSUE THREAD

**Issue by dhruvkb** [lupas/vue3-keypress#6]
In the `README.md`, the `href` for the link 'mapped string' is missing.

https://github.com/lupas/vue3-keypress/blob/35d99ed6bd90457f27562ad14bcbbcccdc0dc586/README.md#L133

If I'm correct, I suppose it should be mapped to the [`key_codes.ts` file](https://github.com/lupas/vue3-keypress/blob/master/packages/vue3-keypress/src/key_codes.ts)?

**Comment by lupas** [comment]
Thanks a lot, I added it to the readme! Appreciate it!

**Comment by dhruvkb** [comment]
Thanks for making and maintaining the plugin. It's very helpful!
